name: Cache Node and NPM Dependencies
description: This action allows to cache both Node and NPM dependencies based on the packaga-lock.json file.

inputs:
  node-version:
    description: Node.js version to use
    default: 25.x
    required: true
  working-dir:
    description: Working Directory of the Application
    default: .
    required: true
  target-env:
    description: dev or prod - Controls whether dev deps are installed
    default: dev
    required: false

runs:
  using: composite
  steps:
    - name: Setup Node.js Version ${{ inputs.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v5
      with:
        path: ${{ inputs.working-dir }}
        key: node-module-deps-${{ hashFiles(format('{0}/{1}', inputs.working-dir, 'package-lock.json')) }}

    - name: Install Dependencies
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        ${{  inputs.target-env == 'dev' && 'npm ci' || 'npm ci --omit=dev'}}
