name: 09 - Using Functions

on:
  pull_request:

jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 3 seconds
        run: sleep 3

      - name: Print PR Title
        run: echo "${{github.event.pull_request.title}}"

      - name: Print Trigger Event Info
        run: |
          cat << EOF
          ${{ toJSON(github.event) }}
          EOF

      - name: Bug Step
        if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix') }}
        run: echo "I'm a bug fix"
    
      - name: Failing step
        run: exit 1

      - name: This step will be skipped
        if: ${{ success() }}
        run: echo "This step will be skipped"

      - name: This step will be runned
        if: ${{ failure() }}
        run: echo "This step will be runned"

      - name: This step always run
        if: ${{ !cancelled() }}
        run: |
          echo "Logging: Trigger event is ${{github.event_name}} from ${{github.head_ref}} to ${{github.base_ref}} and run on ${{runner.os}}"

      - name: This step will execute when cancelled
        if: ${{ cancelled() }}
        run: |
          echo "Logging: Trigger event is ${{github.event_name}}."
