name: 17 - Working with Composite Action

on:
  workflow_dispatch:
    inputs:
      working-directory:
        description: Where you want to workflow working with
        type: string
        default: ./react-app
      target-env:
        description: Which environment to target
        type: choice
        options:
          - dev
          - prod

jobs:
  build:
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Node and NPM Deps
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: 24.x
          working-dir: ${{ inputs.working-directory }}
          target-env: ${{ inputs.target-env }}

      - name: Testing
        run: |
          npm run test

      - name: Building
        run: |
          npm run build
