name: 17.2 - Working with JS Custom Actions

on:
  workflow_dispatch:
        
jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Setup Node and NPM Deps
        uses: ./.github/actions/js-dependency-update
       
