name: 17.2 - Working with JS Custom Actions

on:
  workflow_dispatch:
  issues:
    types: [opened]
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Run my custom action (Log github context)
        uses: ./.github/actions/js-dependency-update
